.TH pass-outdated 1 "December 2021" "pass-outdated"

.SH NAME
pass-outdated \- A \fBpass\fP(1) extension that provides an easy flow detect old passwords.

.SH SYNOPSIS
\fBpass outdated\fP [command]

.SH DESCRIPTION
\fBpass update\fP extends the pass utility with an easy flow to detect old passwords.
